kind = "web"
previewPath = "/"
title = "Smartledger Premium Web3"
version = "1.0.0"
id = "artifacts/user-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24899

[services.development]
run = "npm run dev --workspace @workspace/user-app"

[services.production]
build = [ "npm", "run", "build", "--workspace", "@workspace/user-app" ]
publicDir = "artifacts/user-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24899"
BASE_PATH = "/"
